package net.corevalue.company.hierarchy.exception;

public interface ExceptionConstants {
    String ENTITY_HAS_SUPERVISOR = "====== ENTITY ALREADY HAS SUPERVISOR! AT FIRST YOU NEED TO DETACH THEM!";
    String YOU_ALREADY_SUPERVISE_ENTITY = "====== ENTITY ALREADY SUPERVISED BY YOU!";
    String CONTROL_LOCK = "====== CONTROL LOCK! YOU TRY TO CONTROL EACH OTHER!";
    String DELETE_CONFLICT = "ENTITY NOT FOUND OR CAN'T BE REMOVED! " +
            "IF HE STILL SUPERVISES SOME EMPLOYEES REMOVE HIM FROM ANOTHER EMPLOYEES AS SUPERVISOR!";
    String ID_EQUALITY = "====== ID EQUALS! YOU CAN'T CONTROL YOURSELF!";
    String NOT_FOUND = "ENTITY WITH THIS CRITERIA NOT FOUND";
}